description: >
  A Docker executor using CricleCI's Node.js images optimized for CI.

parameters:
  node_tag:
    type: string
    default: lts
    description: >
      Choose a specific cimg/node image tag:
      https://hub.docker.com/r/cimg/node/tags
  postgres_tag:
    type: string
    default: "16.2"
    description: >
      Choose a specific cimg/postgres image tag:
      https://hub.docker.com/r/cimg/postgres/tags
  resource_class:
    type: enum
    enum:
      ["small", "medium", "medium+", "large", "xlarge", "2xlarge", "2xlarge+"]
    default: "large"
    description: Choose the executor resource class

docker:
  - image: cimg/node:<<parameters.node_tag>>
  - image: cimg/postgres:<<parameters.postgres_tag>>
    environment:
      POSTGRES_DB: circleci_test
      POSTGRES_USER: circleci
      POSTGRES_PASSWORD: circleci_password
resource_class: <<parameters.resource_class>>
